# Generated by Django 3.2.3 on 2021-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210528_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('L', 'Loafer'), ('SL', 'Sleepers'), ('S', 'Sandel'), ('SP', 'Sports'), ('F', 'Formal Shoes'), ('FSL', 'FSleepers'), ('FS', 'FSandel')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
