# Generated by Django 3.2.3 on 2021-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(default='', max_length=2),
        ),
    ]
